[package]
name = "lore-sys"
version = "0.0.0"
authors = ["Traverse Research <support@traverseresearch.nl>"]
edition = "2021"
license = "MIT"
homepage = "https://traverseresearch.nl"
repository = "https://github.com/Traverse-Research/Lore-rust-bindings"
description = "Rust bindings for the Lore C API (Epic Games' Lore version control), pregenerated with bindgen"
include = ["src", "LICENSE"]
categories = ["external-ffi-bindings"]
keywords = ["lore", "bindings", "ffi"]
rust-version = "1.74"

[dependencies]
libloading = "0.8"
