[package]
name = "lore-bin"
version = "0.0.0"
authors = ["Traverse Research"]
edition = "2021"
license = "MIT"
rust-version = "1.74"
homepage = "https://traverseresearch.nl"
repository = "https://github.com/Traverse-Research/lore-rs"
description = "Downloads the prebuilt Lore shared library from the official Lore GitHub releases, for use in build scripts"
publish = false
